local highlights = {
		Normal = {fg = C.fg, bg = Config.transparent_background and "NONE" or C.bg, },
		Comment = {fg = C.gray, style = "italic", },
		Constant = {fg = C.yellow, },
		String = {fg = C.yellow, },
		Character = {fg = C.yellow, },
		Number = {fg = C.orange, },
		Boolean = {fg = C.orange, },
		Float = {fg = C.orange, },
		Identifier = {fg = C.magenta, },
		Function = {fg = C.magenta, },
		Statement = {fg = C.blue, },
		Conditional = {fg = C.blue, },
		Repeat = {fg = C.blue, },
		Label = {fg = C.gray_blue, },
		Operator = {fg = C.gray_blue, },
		Keyword = {fg = C.blue, },
		Exception = {fg = C.blue, },
		PreProc = {fg = C.green, },
		Include = {fg = C.green, },
		Define = {fg = C.green, },
		Title = {fg = C.cyan, },
		Macro = {fg = C.green, },
		PreCondit = {fg = C.light_blue, },
		Type = {fg = C.gray_blue, },
		StorageClass = {fg = C.gray_blue, },
		Structure = {fg = C.gray_blue, },
		Typedef = {fg = C.gray_blue, },
		Special = {fg = C.red, },
		SpecialComment = {fg = C.gray, },
		Error = {fg = C.error_red, style = "bold,reverse", },
		Todo = {fg = C.orange, style = "bold,italic", },
		Underlined = {fg = C.cyan, style = "underline", },
		Cursor = {fg = C.cursor_fg, bg = C.cursor_bg, },
		ColorColumn = {bg = C.cursor_column_gray, },
		CursorLineNr = {fg = C.white, style = "bold", },
		SignColumn = {bg = C.bg, },
		Conceal = {fg = C.darker_gray, },
		CursorColumn = {bg = C.cursor_column_gray, },
		CursorLine = {bg = C.darker_gray, },
		Directory = {fg = C.blue, },
		DiffAdd = {fg = C.black, bg = C.green, },
		DiffChange = {fg = C.yellow, style = "underline", },
		DiffDelete = {fg = C.black, bg = C.red, },
		DiffText = {fg = C.black, bg = C.yellow, },
		ErrorMsg = {fg = C.error_red, },
		VertSplit = {fg = C.vertsplit, },
		Folded = {fg = C.darker_gray, },
		IncSearch = {bg = C.dark_gray2, },
		LineNr = {fg = C.gutter_fg_gray, },
		NonText = {fg = C.special_gray, },
		Pmenu = {fg = C.white, bg = C.menu_gray, },
		PmenuSel = {fg = C.shiny_white, bg = C.dark_gray, },
		PmenuSbar = {bg = C.special_gray, },
		PmenuThumb = {bg = C.white, },
		Question = {fg = C.magenta, },
		QuickFixLine = {bg = C.darker_gray, },
		Search = {bg = C.dark_gray2, },
		SpecialKey = {fg = C.special_gray, },
		SpellBad = {fg = C.error_red, style = "underline", },
		SpellCap = {fg = C.dark_yellow, },
		SpellLocal = {fg = C.dark_yellow, },
		SpellRare = {fg = C.dark_yellow, },
		StatusLine = {fg = C.white, bg = C.darker_gray, },
		StatusLineNC = {fg = C.darker_gray, },
		StatusLineTerm = {fg = C.white, bg = C.darker_gray, },
		StatusLineTermNC = {fg = C.darker_gray, },
		TabLine = {fg = C.darker_gray, },
		TabLineSel = {fg = C.tabsel, },
		TabLineFill = {bg = C.tabfill, },
		Terminal = {fg = C.white, bg = C.black, },
		Visual = {bg = C.dark_gray2, },
		VisualNOS = {fg = C.dark_gray2, },
		WarningMsg = {fg = C.yellow, },
		WildMenu = {fg = C.black, bg = C.blue, },
		EndOfBuffer = {fg = C.bg, },
		TSComment = {fg = C.gray, style = "italic", },
		TSError = {fg = C.error_red, },
		TSPunctDelimiter = {fg = C.red, },
		TSPunctBracket = {fg = C.red, },
		TSPunctSpecial = {fg = C.red, },
		TSConstant = {fg = C.yellow, },
		TSConstBuiltin = {fg = C.blue, },
		TSConstMacro = {fg = C.green, },
		TSStringRegex = {fg = C.yellow, },
		TSString = {fg = C.yellow, },
		TSStringEscape = {fg = C.red, },
		TSCharacter = {fg = C.yellow, },
		TSNumber = {fg = C.orange, },
		TSBoolean = {fg = C.orange, },
		TSFloat = {fg = C.orange, },
		TSAnnotation = {fg = C.green, },
		TSAttribute = {fg = C.light_blue, },
		TSNamespace = {fg = C.blue, },
		TSFuncBuiltin = {fg = C.magenta, },
		TSFunction = {fg = C.magenta, },
		TSFuncMacro = {fg = C.green, },
		TSParameter = {fg = C.white, },
		TSParameterReference = {fg = C.white, },
		TSMethod = {fg = C.magenta, },
		TSField = {fg = C.white, },
		TSProperty = {fg = C.magenta, },
		TSConstructor = {fg = C.magenta, },
		TSConditional = {fg = C.gray_blue, },
		TSRepeat = {fg = C.blue, },
		TSLabel = {fg = C.light_blue, },
		TSKeyword = {fg = C.blue, },
		TSKeywordFunction = {fg = C.gray_blue, },
		TSKeywordOperator = {fg = C.blue, },
		TSOperator = {fg = C.gray_blue, },
		TSException = {fg = C.blue, },
		TSType = {fg = C.gray_blue, },
		TSTypeBuiltin = {fg = C.gray_blue, },
		TSStructure = {fg = C.gray_blue, },
		TSInclude = {fg = C.green, },
		TSVariable = {fg = C.white, },
		TSVariableBuiltin = {fg = C.white, },
		TSText = {fg = C.fg, },
		TSStrong = {fg = C.green, },
		TSEmphasis = {fg = C.magenta, },
		TSUnderline = {fg = C.red, },
		TSTitle = {fg = C.fg, },
		TSLiteral = {fg = C.gray, },
		TSURI = {style = "underline", },
		TSTag = {fg = C.blue, },
		TSTagDelimiter = {fg = C.red, },
		TSQueryLinterError = {fg = C.warning_orange, },
		htmlArg = {fg = C.magenta, },
		htmlBold = {fg = C.magenta, style = "bold", },
		htmlEndTag = {fg = C.white, },
		htmlH1 = {fg = C.blue, },
		htmlH2 = {fg = C.blue, },
		htmlH3 = {fg = C.blue, },
		htmlH4 = {fg = C.blue, },
		htmlH5 = {fg = C.blue, },
		htmlH6 = {fg = C.blue, },
		htmlItalic = {fg = C.magenta, style = "italic", },
		htmlLink = {fg = C.cyan, style = "underline", },
		htmlSpecialChar = {fg = C.red, },
		htmlSpecialTagName = {fg = C.magenta, },
		htmlTag = {fg = C.magenta, },
		htmlTagN = {fg = C.blue, },
		htmlTagName = {fg = C.blue, },
		htmlTitle = {fg = C.white, },
		htmlValue = {fg = C.magenta, },
		markdownBlockquote = {fg = C.darker_gray, },
		markdownBold = {fg = C.magenta, style = "bold", },
		markdownCode = {fg = C.gray_blue, },
		markdownCodeBlock = {fg = C.white, },
		markdownCodeDelimiter = {fg = C.red, },
		markdownH1 = {fg = C.magenta, },
		markdownH2 = {fg = C.magenta, },
		markdownH3 = {fg = C.magenta, },
		markdownH4 = {fg = C.magenta, },
		markdownH5 = {fg = C.magenta, },
		markdownH6 = {fg = C.magenta, },
		markdownHeadingDelimiter = {fg = C.green, },
		markdownHeadingRule = {fg = C.darker_gray, },
		markdownId = {fg = C.magenta, },
		markdownIdDeclaration = {fg = C.blue, },
		markdownIdDelimiter = {fg = C.red, },
		markdownItalic = {fg = C.magenta, style = "italic", },
		markdownLinkDelimiter = {fg = C.red, },
		markdownLinkText = {fg = C.blue, },
		markdownListMarker = {fg = C.magenta, },
		markdownOrderedListMarker = {fg = C.magenta, },
		markdownRule = {fg = C.darker_gray, },
		markdownUrl = {fg = C.cyan, style = "underline", },
		CocExplorerIndentLine = {fg = C.medium_gray, },
		CocExplorerBufferRoot = {fg = C.yellow, },
		CocExplorerFileRoot = {fg = C.yellow, },
		CocExplorerBufferFullPath = {fg = C.light_gray, },
		CocExplorerFileFullPath = {fg = C.light_gray, },
		CocExplorerBufferReadonly = {fg = C.magenta, },
		CocExplorerBufferModified = {fg = C.magenta, },
		CocExplorerBufferNameVisible = {fg = C.orange, },
		CocExplorerFileReadonly = {fg = C.magenta, },
		CocExplorerFileModified = {fg = C.green, },
		CocExplorerFileHidden = {fg = C.special_gray, },
		CocExplorerHelpLine = {fg = C.magenta, },
		EasyMotionTarget = {fg = C.error_red, style = "bold", },
		EasyMotionTarget2First = {fg = C.error_red, style = "bold", },
		EasyMotionTarget2Second = {fg = C.error_red, style = "bold", },
		StartifyNumber = {fg = C.red, },
		StartifySelect = {fg = C.green, },
		StartifyBracket = {fg = C.blue, },
		StartifySpecial = {fg = C.cyan, },
		StartifyVar = {fg = C.blue, },
		StartifyPath = {fg = C.blue, },
		StartifyFile = {fg = C.cyan, },
		StartifySlash = {fg = C.blue, },
		StartifyHeader = {fg = C.light_blue, },
		StartifySection = {fg = C.magenta, },
		StartifyFooter = {fg = C.green, },
		WhichKey = {fg = C.magenta, },
		WhichKeySeperator = {fg = C.green, },
		WhichKeyGroup = {fg = C.vivid_blue, },
		WhichKeyDesc = {fg = C.blue, },
		diffAdded = {fg = C.green, },
		diffAdd = {fg = C.green, },
		diffRemoved = {fg = C.red, },
		diffFileId = {fg = C.blue, style = "bold,reverse", },
		diffFile = {fg = C.gray_blue, },
		diffNewFile = {fg = C.green, },
		diffOldFile = {fg = C.red, },
		debugPc = {bg = C.cyan, },
		debugBreakpoint = {fg = C.red, style = "reverse", },
		GitSignsAdd = {fg = C.green, },
		GitSignsChange = {fg = C.blue, },
		GitSignsDelete = {fg = C.red, },
		LspDiagnosticsUnderlineHint = {fg = C.gray, },
		LspDiagnosticsSignError = {fg = C.error_red, },
		LspDiagnosticsSignWarning = {fg = C.warning_orange, },
		LspDiagnosticsSignInformation = {fg = C.info_yellow, },
		LspDiagnosticsSignHint = {fg = C.vivid_blue, },
		LspDiagnosticsVirtualTextError = {fg = C.error_red, },
		LspDiagnosticsVirtualTextWarning = {fg = C.warning_orange, },
		LspDiagnosticsVirtualTextInformation = {fg = C.info_yellow, },
		LspDiagnosticsVirtualTextHint = {fg = C.vivid_blue, },
		QuickScopePrimary = {fg = C.vivid_blue, style = "underline", },
		QuickScopeSecondary = {fg = C.red, style = "underline", },
		MatchWord = {style = "underline", },
		MatchParen = {style = "underline", },
		MatchWordCur = {style = "underline", },
		MatchParenCur = {style = "underline", },
		NvimTreeImageFile = {fg = C.magenta, },
		NvimTreeGitDirty = {fg = C.git_green, },
		NvimTreeGitDeleted = {fg = C.git_green, },
		NvimTreeGitStaged = {fg = C.git_green, },
		NvimTreeGitMerge = {fg = C.git_green, },
		NvimTreeGitRenamed = {fg = C.git_green, },
		NvimTreeGitNew = {fg = C.git_green, },
		NvimTreeIndentMarker = {fg = C.medium_gray, },
		NvimTreeSymlink = {fg = C.symlink, },
		NvimTreeFolderIcon = {fg = C.blue, },
		NvimTreeRootFolder = {fg = C.lighter_gray, style = "bold", },
		NvimTreeExecFile = {fg = C.executable, },
		NvimTreeSpecialFile = {fg = C.magenta, },
		NvimTreeLspDiagnostics = {fg = C.warning_orange, },
		BufferCurrent = {fg = C.fg, bg = C.bg, },
		BufferCurrentIndex = {fg = C.blue, bg = C.bg, },
		BufferCurrentMod = {fg = C.fg, bg = C.bg, },
		BufferCurrentSign = {fg = C.blue, bg = C.bg, },
		BufferCurrentTarget = {fg = C.red, bg = C.bg, style = "bold", },
		BufferVisible = {fg = C.fg, bg = C.bg, },
		BufferVisibleIndex = {fg = C.fg, bg = C.bg, },
		BufferVisibleMod = {fg = C.fg, bg = C.bg, },
		BufferVisibleSign = {fg = C.fg, bg = C.bg, },
		BufferVisibleTarget = {fg = C.red, bg = C.bg, style = "bold", },
		BufferInactive = {fg = C.gutter_fg_gray, bg = C.bg_inactive, },
		BufferInactiveIndex = {fg = C.gutter_fg_gray, bg = C.bg_inactive, },
		BufferInactiveMod = {fg = C.gutter_fg_gray, bg = C.bg_inactive, },
		BufferInactiveSign = {fg = C.gutter_fg_gray, bg = C.bg_inactive, },
		BufferInactiveTarget = {fg = C.red, bg = C.bg_inactive, style = "bold", },
		CodiVirtualText = {fg = C.magenta, },
		IndentBlanklineContextChar = {fg = C.indentlinehighlight, },
		DashboardHeader = {fg = C.blue, },
		DashboardCenter = {fg = C.magenta, },
		DashboardFooter = {fg = C.light_blue, },
		WhichKeyFloat = {fg = C.bg, },
		VimwikiHeader1 = {fg = C.magenta, style = "bold", },
		VimwikiHeader2 = {fg = C.green, style = "bold", },
		VimwikiHeader3 = {fg = C.blue, style = "bold", },
		VimwikiHeader4 = {fg = C.cyan, style = "bold", },
		VimwikiHeader5 = {fg = C.dark_yellow, style = "bold", },
		VimwikiHeader6 = {fg = C.magenta, style = "bold", },
		VimwikiLink = {fg = C.vivid_blue, },
		VimwikiHeaderChar = {fg = C.darker_gray, },
		VimwikiHR = {fg = C.yellow, },
		VimwikiList = {fg = C.magenta, },
		VimwikiTag = {fg = C.magenta, },
		VimwikiMarkers = {fg = C.darker_gray, },
}

return highlights