local highlights = {
		Normal = {fg = C.fg, bg = Config.transparent_background and "NONE" or C.bg, },
		Comment = {fg = C.line_grey, style = "italic", },
		Constant = {fg = C.yellow, },
		String = {fg = C.yellow, },
		Character = {fg = C.green, },
		Number = {fg = C.orange, },
		Boolean = {fg = C.cyan, },
		Float = {fg = C.orange, },
		Identifier = {fg = C.cyan, },
		Function = {fg = C.yellow, },
		Statement = {fg = C.purple, },
		Conditional = {fg = C.pink, },
		Repeat = {fg = C.purple, },
		Label = {fg = C.cyan, },
		Operator = {fg = C.purple, },
		Keyword = {fg = C.cyan, },
		Exception = {fg = C.purple, },
		PreProc = {fg = C.yellow, },
		Include = {fg = C.purple, },
		Define = {fg = C.purple, },
		Title = {fg = C.cyan, },
		Macro = {fg = C.purple, },
		PreCondit = {fg = C.cyan, },
		Type = {fg = C.cyan, style = "italic", },
		StorageClass = {fg = C.pink, },
		Structure = {fg = C.yellow, },
		Typedef = {fg = C.yellow, },
		Special = {fg = C.green, style = "italic", },
		SpecialComment = {fg = C.line_grey, },
		Error = {fg = C.error_red, style = "bold,reverse", },
		Todo = {fg = C.purple, style = "bold,italic", },
		Underlined = {fg = C.cyan, style = "underline", },
		Cursor = {style = "reverse", },
		ColorColumn = {bg = C.cursor_grey, },
		CursorLineNr = {fg = C.white, style = "bold", },
		SignColumn = {bg = C.bg, },
		Conceal = {fg = C.line_grey, },
		CursorColumn = {bg = C.cursor_grey, },
		CursorLine = {bg = C.cursor_grey, },
		Directory = {fg = C.cyan, },
		DiffAdd = {fg = C.black, bg = C.green, },
		DiffChange = {fg = C.orange, },
		DiffDelete = {fg = C.red, },
		DiffText = {fg = C.line_grey, },
		ErrorMsg = {fg = C.error_red, },
		VertSplit = {fg = C.vertsplit, },
		Folded = {fg = C.line_grey, },
		IncSearch = {fg = C.yellow, bg = C.line_grey, },
		LineNr = {fg = C.line_grey, },
		MatchParen = {fg = C.fg, style = "underline", },
		NonText = {fg = C.special_grey, },
		Pmenu = {fg = C.white, bg = C.menu_grey, },
		PmenuSel = {fg = C.black, bg = C.cyan, },
		PmenuSbar = {bg = C.special_grey, },
		PmenuThumb = {bg = C.white, },
		Question = {fg = C.purple, },
		QuickFixLine = {fg = C.black, bg = C.yellow, },
		Search = {fg = C.black, bg = C.yellow, },
		SpecialKey = {fg = C.special_grey, },
		SpellBad = {fg = C.error_red, style = "underline", },
		SpellCap = {fg = C.yellow, },
		SpellLocal = {fg = C.yellow, },
		SpellRare = {fg = C.yellow, },
		StatusLine = {fg = C.white, bg = C.cursor_grey, },
		StatusLineNC = {fg = C.line_grey, },
		StatusLineTerm = {fg = C.white, bg = C.cursor_grey, },
		StatusLineTermNC = {fg = C.cursor_grey, },
		TabLine = {fg = C.line_grey, },
		TabLineSel = {fg = C.white, },
		TabLineFill = {bg = C.bg, },
		Terminal = {fg = C.white, bg = C.black, },
		Visual = {bg = C.visual_grey, },
		VisualNOS = {fg = C.visual_grey, },
		WarningMsg = {fg = C.yellow, },
		WildMenu = {fg = C.black, bg = C.cyan, },
		EndOfBuffer = {fg = C.black, },
		TSError = {fg = C.error_red, },
		TSPunctDelimiter = {fg = C.fg, },
		TSPunctBracket = {fg = C.fg, },
		TSPunctSpecial = {fg = C.fg, },
		TSConstant = {fg = C.purple, },
		TSConstBuiltin = {fg = C.purple, },
		TSConstMacro = {fg = C.cyan, },
		TSStringRegex = {fg = C.red, },
		TSString = {fg = C.yellow, },
		TSStringEscape = {fg = C.cyan, },
		TSCharacter = {fg = C.green, },
		TSNumber = {fg = C.purple, },
		TSBoolean = {fg = C.purple, },
		TSFloat = {fg = C.green, },
		TSAnnotation = {fg = C.yellow, },
		TSAttribute = {fg = C.cyan, },
		TSNamespace = {fg = "#FF00FF", },
		TSFuncBuiltin = {fg = C.cyan, },
		TSFunction = {fg = C.green, },
		TSFuncMacro = {fg = C.green, },
		TSParameter = {fg = C.orange, },
		TSParameterReference = {fg = C.orange, },
		TSMethod = {fg = C.green, },
		TSField = {fg = C.orange, },
		TSProperty = {fg = C.fg, },
		TSConstructor = {fg = C.cyan, },
		TSConditional = {fg = C.pink, },
		TSRepeat = {fg = C.pink, },
		TSLabel = {fg = C.cyan, },
		TSKeyword = {fg = C.pink, },
		TSKeywordFunction = {fg = C.cyan, },
		TSKeywordOperator = {fg = C.pink, },
		TSOperator = {fg = C.pink, },
		TSException = {fg = C.purple, },
		TSType = {fg = C.pink, },
		TSTypeBuiltin = {fg = C.cyan, style = "italic", },
		TSStructure = {fg = C.purple, },
		TSInclude = {fg = C.pink, },
		TSVariable = {fg = C.fg, },
		TSVariableBuiltin = {fg = C.purple, },
		TSText = {fg = "#FFFF00", },
		TSStrong = {fg = "#FFFF00", },
		TSEmphasis = {fg = "#FFFF00", },
		TSUnderline = {fg = "#FFFF00", },
		TSTitle = {fg = "#FFFF00", },
		TSLiteral = {fg = "#FFFF00", },
		TSURI = {fg = "#FFFF00", },
		TSTag = {fg = C.cyan, },
		TSTagDelimiter = {fg = C.white, },
		htmlArg = {fg = C.yellow, },
		htmlBold = {fg = C.yellow, style = "bold", },
		htmlEndTag = {fg = C.white, },
		htmlH1 = {fg = C.pink, },
		htmlH2 = {fg = C.pink, },
		htmlH3 = {fg = C.pink, },
		htmlH4 = {fg = C.pink, },
		htmlH5 = {fg = C.pink, },
		htmlH6 = {fg = C.pink, },
		htmlItalic = {fg = C.purple, style = "italic", },
		htmlLink = {fg = C.green, style = "underline", },
		htmlSpecialChar = {fg = C.yellow, },
		htmlSpecialTagName = {fg = C.cyan, },
		htmlTag = {fg = C.pink, },
		htmlTagN = {fg = C.pink, },
		htmlTagName = {fg = C.cyan, },
		htmlTitle = {fg = C.white, },
		markdownBlockquote = {fg = C.yellow, style = "italic", },
		markdownBold = {fg = C.orange, style = "bold", },
		markdownCode = {fg = C.green, },
		markdownCodeBlock = {fg = C.orange, },
		markdownCodeDelimiter = {fg = C.red, },
		markdownH1 = {fg = C.pink, style = "bold", },
		markdownH2 = {fg = C.pink, style = "bold", },
		markdownH3 = {fg = C.pink, style = "bold", },
		markdownH4 = {fg = C.pink, style = "bold", },
		markdownH5 = {fg = C.pink, style = "bold", },
		markdownH6 = {fg = C.pink, style = "bold", },
		markdownHeadingDelimiter = {fg = C.red, },
		markdownHeadingRule = {fg = C.line_grey, },
		markdownId = {fg = C.purple, },
		markdownIdDeclaration = {fg = C.cyan, },
		markdownIdDelimiter = {fg = C.purple, },
		markdownItalic = {fg = C.yellow, style = "italic", },
		markdownLinkDelimiter = {fg = C.purple, },
		markdownLinkText = {fg = C.pink, },
		markdownListMarker = {fg = C.cyan, },
		markdownOrderedListMarker = {fg = C.red, },
		markdownRule = {fg = C.line_grey, },
		markdownUrl = {fg = C.cyan, style = "underline", },
		CocExplorerIndentLine = {fg = C.line_grey, },
		CocExplorerBufferRoot = {fg = C.cyan, },
		CocExplorerFileRoot = {fg = C.cyan, },
		CocExplorerBufferFullPath = {fg = C.line_grey, },
		CocExplorerFileFullPath = {fg = C.line_grey, },
		CocExplorerBufferReadonly = {fg = C.red, },
		CocExplorerBufferModified = {fg = C.purple, },
		CocExplorerBufferNameVisible = {fg = C.green, },
		CocExplorerFileReadonly = {fg = C.red, },
		CocExplorerFileModified = {fg = C.purple, },
		CocExplorerFileHidden = {fg = C.line_grey, },
		CocExplorerHelpLine = {fg = C.purple, },
		EasyMotionTarget = {fg = C.error_red, style = "bold", },
		EasyMotionTarget2First = {fg = C.error_red, style = "bold", },
		EasyMotionTarget2Second = {fg = C.error_red, style = "bold", },
		StartifyNumber = {fg = C.orange, },
		StartifySelect = {fg = C.green, },
		StartifyBracket = {fg = C.pink, },
		StartifySpecial = {fg = C.cyan, },
		StartifyVar = {fg = C.pink, },
		StartifyPath = {fg = C.cyan, },
		StartifyFile = {fg = C.red, },
		StartifySlash = {fg = C.pink, },
		StartifyHeader = {fg = C.green, },
		StartifySection = {fg = C.purple, },
		StartifyFooter = {fg = C.green, },
		WhichKey = {fg = C.purple, },
		WhichKeySeperator = {fg = C.green, },
		WhichKeyGroup = {fg = C.cyan, },
		WhichKeyDesc = {fg = C.cyan, },
		diffAdded = {fg = C.green, },
		diffRemoved = {fg = C.red, },
		diffFileId = {fg = C.yellow, style = "bold,reverse", },
		diffFile = {fg = C.special_grey, },
		diffNewFile = {fg = C.green, },
		diffOldFile = {fg = C.red, },
		debugPc = {bg = C.cyan, },
		debugBreakpoint = {fg = C.red, style = "reverse", },
		VimwikiHeader1 = {fg = C.orange, style = "bold", },
		VimwikiHeader2 = {fg = C.green, style = "bold", },
		VimwikiHeader3 = {fg = C.pink, style = "bold", },
		VimwikiHeader4 = {fg = C.cyan, style = "bold", },
		VimwikiHeader5 = {fg = C.yellow, style = "bold", },
		VimwikiHeader6 = {fg = C.purple, style = "bold", },
		VimwikiLink = {fg = C.cyan, },
		VimwikiHeaderChar = {fg = C.line_grey, },
		VimwikiHR = {fg = C.yellow, },
		VimwikiList = {fg = C.orange, },
		VimwikiTag = {fg = C.orange, },
		VimwikiMarkers = {fg = C.line_grey, },
}

return highlights